image: golang:latest
pipelines:
  default:
    - step:
        script:
          - mkdir -p "$GOPATH/src/github.com/jitsi"
          - ln -s "`pwd`" "$GOPATH/src/github.com/jitsi/jwtsi"
          - go version
          - cd "$GOPATH/src/github.com/jitsi/jwtsi"
          - go-wrapper download
          - go build -race
          - go vet
          - go test -cover
          - cd "$GOPATH/src/github.com/jitsi/jwtsi/jwtsi"
          - go-wrapper download
          - go build -race
          - go vet
          - go test -cover
